### ISSUE TITLE
[Script idea] Modify vocal mode parameters beyond their set limits

### ISSUE THREAD

**Issue by Susko3** [claire-west/svstudio-scripts#1]
People seem to [manually](https://twitter.com/NanaMelodica/status/1586550289951297536) change vocal modes beyond their limits in notepad, and SynthV doesn't seem to constraint these changes to values that can be set in the UI (0-130%).

Example change in the `.svp` (I'm guessing, as I don't have SynthV Pro):

```diff
"voice": {
    "paramTension": 0.3,
    "vocalModeInherited": false,
    "vocalModePreset": "Customized",
    "vocalModeParams": {
        "Soft": 70.0,
        "Clear": 30.0,
        "Airy": 15.0,
-       "Power": 130.0
+       "Power": 300.0
    }
}
```

Being able to modify vocal modes with a script would be useful, as I'm guessing that the current (notepad) method is hard to use and requires restarting SynthV or reloading the `.svp`.

Script implementation
---

The `voice` object can be accessed in scripts trough [`NoteGroupReference.getVoice()`](https://resource.dreamtonics.com/scripting/NoteGroupReference.html#getVoice) and [`.setVoice()`](https://resource.dreamtonics.com/scripting/NoteGroupReference.html#setVoice).

If `vocalModeParams` are available in this object and can be freely set, showing a message box allowing the user to input a custom percentage should work well.

Some examples of the `voice` object (as stored in the `.svp`)
---

(The non-vocal mode params match the [docs](https://resource.dreamtonics.com/scripting/NoteGroupReference.html#getVoice).)

```json
"voice": {
    "paramLoudness": 3.700000047683716,
    "paramTension": 0.5699999928474426,
    "paramToneShift": -95.0,
    "vocalModeInherited": false,
    "vocalModePreset": "Customized",
    "vocalModeParams": {
        "Clear": 35.0,
        "Solid": 100.0,
        "Power": 120.0,
        "Passionate": 40.0
    }
}
```

```json
"voice": {
    "vocalModeInherited": false,
    "vocalModePreset": "Customized",
    "vocalModeParams": {
        "Soft": 150.0
    }
}
```

```json
"voice": {
    "vocalModeInherited": true,
    "vocalModePreset": "",
    "vocalModeParams": {}
},
```

**Comment by cv4x** [comment]
Looked into it but unfortunately `NoteGroupReference.getVoice()` doesn't include vocal mode settings. I also iterated through the functions of `NoteGroupReference` to see if there were any undocumented ones added, but no luck there either.

I've updated this feature request thread to include access to newly introduced properties: https://forum.synthesizerv.com/t/topic/6704
